"""creat new table user

Revision ID: 3b81ab9b2b80
Revises: b3652bbc3f4e
Create Date: 2022-10-09 02:22:21.978483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b81ab9b2b80'
down_revision = 'b3652bbc3f4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('m_data', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('info', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'info')
    op.drop_column('messages', 'm_data')
    # ### end Alembic commands ###
